# Generated by Django 5.0.2 on 2024-02-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="usuario",
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
