# Generated by Django 4.2.8 on 2024-02-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_usuario_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status_flag",
            field=models.CharField(
                default='<span class="fa fa-check-square-o fa-lg" style="color:green; font-size:20px;"></span>',
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
