# Generated by Django 4.2.8 on 2024-02-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_status_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="E-email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Administrador?"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False, verbose_name="Super Administrador?"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nome",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="user",
            name="status_flag",
            field=models.CharField(max_length=200, verbose_name="Status Flag"),
        ),
        migrations.AlterField(
            model_name="user",
            name="telefone",
            field=models.CharField(max_length=15, verbose_name="Telefone"),
        ),
    ]
