# Generated by Django 5.0.2 on 2024-02-24 02:55

import stdimage.models
from django.db import migrations, models

import vitimas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vitima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("data_joined", models.DateTimeField(auto_now_add=True)),
                ("last_edition", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                ("rg", models.CharField(max_length=10, verbose_name="Registro Geral")),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                ("endereco", models.CharField(max_length=120, verbose_name="Endereço")),
                ("telefone", models.CharField(max_length=18, verbose_name="Telefone")),
                ("suspeito", models.CharField(max_length=120, verbose_name="Suspeito")),
                (
                    "chave_acesso",
                    models.CharField(default="", editable=False, max_length=15),
                ),
                (
                    "foto_vitima",
                    stdimage.models.StdImageField(
                        default="avatarPadraoVitima.jpg",
                        force_min_size=False,
                        upload_to=vitimas.models.get_file_path,
                        variations={
                            "thumb": {
                                "crop": True,
                                "height": 212,
                                "resample": True,
                                "width": 212,
                            }
                        },
                        verbose_name="Foto da Vítima",
                    ),
                ),
                (
                    "foto_suspeito",
                    stdimage.models.StdImageField(
                        default="avatarPadraoSuspeito.jpg",
                        force_min_size=False,
                        upload_to=vitimas.models.get_file_path,
                        variations={
                            "thumb": {
                                "crop": True,
                                "height": 212,
                                "resample": True,
                                "width": 212,
                            }
                        },
                        verbose_name="Foto do Suspeito",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank="", null=True, verbose_name="Observações"),
                ),
            ],
            options={
                "verbose_name": "Vitima",
                "verbose_name_plural": "Vitimas",
            },
        ),
    ]
