# Generated by Django 4.2.8 on 2024-02-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitimas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitima",
            name="status_flag",
            field=models.CharField(
                default=None, max_length=200, verbose_name="Status Flag"
            ),
            preserve_default=False,
        ),
    ]
