# Generated by Django 4.2.8 on 2024-02-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitimas", "0002_vitima_status_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitima",
            name="access_key",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitima",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vitima",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="vitima",
            name="password",
            field=models.CharField(
                default=None, max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vitima",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
