# Generated by Django 4.2.8 on 2024-02-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vitimas", "0004_rename_data_joined_vitima_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vitima",
            name="access_key",
        ),
    ]
