# Generated by Django 4.2.8 on 2024-03-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitimas", "0005_remove_vitima_access_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitima",
            name="status_flag",
            field=models.CharField(
                blank="", max_length=200, null=True, verbose_name="Status Flag"
            ),
        ),
    ]
