# Generated by Django 4.2.8 on 2024-03-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitimas", "0006_alter_vitima_status_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitima",
            name="status_flag",
            field=models.CharField(
                default="", max_length=200, null=True, verbose_name="Status Flag"
            ),
        ),
    ]
