# Generated by Django 4.2.8 on 2024-03-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitimas", "0008_alter_vitima_status_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitima",
            name="chave_acesso",
            field=models.CharField(default="", editable=False, max_length=15),
        ),
    ]
