# Generated by Django 4.2.8 on 2024-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitimas", "0009_vitima_chave_acesso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitima",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
    ]
