# Generated by Django 5.0.2 on 2024-02-24 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vitimas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=10, max_digits=20, verbose_name="Lat"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=10, max_digits=20, verbose_name="Lon"
                    ),
                ),
                (
                    "vitima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vitimas.vitima"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrencia",
                "verbose_name_plural": "Ocorrencias",
            },
        ),
    ]
